- name: Crear estructura de directorios
  file:
    path: "{{ item }}"
    state: directory
  with_items:
 - /tmp/2do_parcial/alumno
 - /tmp/2do_parcial/equipo,



- name: Generar datos del alumno
  template:
   src: datos_alumno.txt.j2
   dest: /tmp/2do_parcial/alumno/datos_alumno.txt,

- name: Generar datos del equipo
  template:
   src: datos_equipo.txt.j2
   dest: /tmp/2do_parcial/equipo/datos_equipo.txt,

- name: Configurar sudoers
  lineinfile:
   dest: /etc/sudoers
   line: "%2PSupervisores ALL=(ALL) NOPASSWD:ALL"
   validate: 'visudo -cf %s'
